spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:30764/springcloud?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 84fWofwZv6
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.foxfairy.base.api

server:
  port: 8084
